<?
$ListItems = Array(
    "Situations" => Array(
        'Write up a tree',
        'Write in a hammock',
        'Write in the bus',
        'Write on the beach',
        'Write on the rooftop of a building',
        'Write on a balcony',
        'Write while at a party',
        'Write while on a road trip',
        'Write while in a blanket fort',
        'Write naked',
        'Write drunk',
        'Write naked AND drunk',
        'Write upside down for 5 minutes',
        'Write while standing up',
        'Write outside during the first snowfall of the year',
        'Write outside during a wind storm',
        'Be writing at 1:01am exactly',
        'Be writing at 12pm noon exactly',
        'Do a word war with only one hand',
        'Write longhand for 1 hour',
        'Write longhand for 5 hours',
        'Write 250 words on your phone',
        'Write 500 words on your phone',
        'Write 1000 words on your phone',
        'Write for 20 minutes on your phone',
        'Write for 45 minutes on your phone',
        'Write for 90 minutes on your phone',
        'Do not turn off autocorrect; use what it gives you',
        'Write with your eyes closed for 30 seconds',
        'Take a weekend off of writing',
        'Beat a Wrimo at a word war',
        'Win a word war against all Wrimos present in your chat',
        'Increase your writing speed record by 250 more words',
        'Complete a one handed word war',
        'Give 10% of your free time to writing',
        'Write a word war on a touch screen'),
    "Daily" => Array(
        '2,000 words in 1 day',
        '3,000 words in 1 day',
        '5,000 words in 1 day',
        '10,000 words in 1 day',
        '12,500 words in 1 day',
        '25,000 words in 1 day'),
    "50k" => Array(
        '5,000 words over weekend',
        '10,000 words over weekend',
        '12,500 words over weekend',
        '25,000 words over weekend',
        '50,000 words over weekend'),
    "Wordcount" => Array(
        'Participate in DORG (Day One Ridiculous Goal)',
        'Beat your previous DORG record',
        'Participate in 50k Weekend Challenge',
        'Beat your 50k Weekend record',
        'Be 10% over your daily requirement',
        'Be 25% over your daily requirement',
        'Be 33% over your daily requirement',
        'Be 10% better than your hourly best',
        'Be 25% better than your hourly best',
        'Write in excess of your daily requirement for 2 days',
        'Write in excess of your daily requirement for 5 days',
        'Write 25k in a single week',
        'Write 1,000 words in every room of your domicile'),
    "Subject" => Array(
        'Insert the Shovel of Death into your novel',
        'Insert a Wrimo as a character of any importance',
        'Insert two or more Wrimos as characters of any importance',
        'Do not use the letter T for 5000 words',
        'Use every letter of the alphabet within 5 setences',
        'Write a cannibalism scene',
        'Write a dream sequence',
        'Write a moment of romance',
        'Write a moment of horror',
        'Write a moment of comedy',
        'Insert monsters and giant mecha in your novel',
        'Insert talking animals into your novel',
        'Make a list of 3-5 household tasks, complete each one, then write a scene where a character completes the exact same tasks'),
    "Long-Term" => Array(
        'Write 1,667 words every day of the month',
        'Increase your average wpm across a series of 5 days (each day higher than the last)',
        'Catch up with someone ahead of you (multiplier handicaps allowed)'),
    "Completion" => Array(
        'Finish 1 book in a week',
        'Finish 1 book in less than 15 days',
        'Finish 1 book in a month',
        'Finish 2 books in a month',
        'Complete 50k weekend',
        'Complete DORG',
        'Defeat 5 obstacles in 5 hours',
        'Defeat 10 obstacles in 5 hours',
        'Defeat 2 obstacles per category',
        'Complete another bingo card in 1 week',
        'Complete 3 bingo cards in a month'),
    "Positivity" => Array(
        'Go 1 day without complaining to anyone, even yourself',
        'Go 1 day without comparing yourself to anyone',
        'Go 1 week without complaining to anyone, even yourself',
        'Go 1 week without comparing yourself to anyone',
        'Write something encouraging to someone once per day for 5 days on the forums',
        'Send 1 encouraging nanomail to someone whom is struggling',
        'Send 1 encouraging nanomail to 5 someones whom are struggling',
        'Send 1 encouraging nanomail to one of your MLs',
        'Send 1 encouraging nanomail to NaNoWriMo staff'),
    "Life" => Array(
        'Do not sign on to social media during 1 writing session (chat and forums included)',
        'Do not sign in to social media for 1 day',
        'Ignore your pets for 60 minutes',
        'Complete all homework and housework for 1 day before writing',
        'Complete all homework and housework for 1 week before writing',
        'Say to friends/family not doing NaNoWriMo "I must go to war; we shall see each other amongst the gods in 1 hour!"',
        'Drink no caffeine for 1 day',
        'Drink no caffeine for 5 days',
        'Drink no caffeine for 2 weeks',
        'Indulge in one non-writing activity to relax your mind and body',
        'Go on a 30 minute walk before writing for 1 day',
        'Go on a 30 minute walk before writing for 3 days',
        'Bake a batch of cookies',
        'Spend 1 afternoon outdoors away from any electronics')
    );
?>
